### ISSUE TITLE
MINOR: **Unable to submit new interests**

### ISSUE THREAD

**Issue by thoalala** [HappyHobby/HappyHobby#49]
**Describe the bug**
I could not find the "Hobby Submission" in the drop-down menu after clicking on my profile picture at the top right-hand corner of the page. 

**To Reproduce**
1. Go to 'Habby Hobby Homepage'
2. Hover on 'Hi, TN'
3. Scroll down to 'Settings/ Logout drop-down menu'

**Expected behavior**
I expected to be able to submit my own interest after reading the "What if my interest is not listed on the website?" on the FAQ. I should be able to find "Hobby Submission" in the drop-down menu after clicking my profile picture at the top right-hand corner of the page.
**Screenshots**
![image](https://user-images.githubusercontent.com/24668595/83665670-986e8c00-a580-11ea-991e-f7cfb4605734.png)

**Additional context**
This is problematic for the functionality of the app. If users cannot find the submission option, they are unable to add new hobbies.

**Comment by thejameskim** [comment]
Closing this issue because this feature was not part of our initial release. The FAQ page is ahead of its time. Updated the FAQ page to not include this feature.
