### ISSUE TITLE
MINOR: "Today's daily hobby..."

### ISSUE THREAD

**Issue by rachelvuu** [HappyHobby/HappyHobby#52]
**Description of issue**:
On the Happy Hobby page, all of the recommendations insert the activity into the string unnaturally 

**Reproduction of steps**:
1. Be logged in and have at least one interest added.
2. Go to 'Happy Hobby' tab
3. Read large text on the right underneath "Hi (user's name)"

**Rationale**: 
Because of the phrasing of the recommendation (e.g. "Today's daily hobby is Music, try Sing Out"), it seems like the activity (sing out) is a proper noun or should be a linked to a resource. I would recommend normalizing the activities so it reads more naturally (e.g. "Today's daily hobby is Photography, try taking pictures on a walk!")

**Additional context**:
Good job on your application, the functionality works really well—this issue is more of a comprehension issue I guess? Also, noticed your footer doesn't stick to the bottom of the screen when there isn't enough content to fill the screen. Other than that, great work!

**Comment by thejameskim** [comment]
thank you for the report on the phrasing issue! closing this issue because both phrasing and footer have been fixed
