### ISSUE TITLE
[Minor] Inconsistent use of word HobbyLobby

### ISSUE THREAD

**Issue by gcaelin30** [HappyHobby/HappyHobby#58]
Super minor here but in the FAQ page, the terms HobbyLobby and Hobby Lobby are both used?

**Comment by thejameskim** [comment]
I'm assuming you meant HappyHobby and Happy Hobby. Thanks for pointing that out!

Closing this issue ~ fixed at [https://github.com/HappyHobby/HappyHobby/commit/49bc93326fcacfc3b8e6675dd39bc8a31f9ed2a6](https://github.com/HappyHobby/HappyHobby/commit/49bc93326fcacfc3b8e6675dd39bc8a31f9ed2a6)
