### ISSUE TITLE
[Major] As soon as I created an account, got stuck on loading

### ISSUE THREAD

**Issue by gcaelin30** [HappyHobby/HappyHobby#59]
<img width="1280" alt="Screen Shot 2020-06-04 at 11 23 28 PM" src="https://user-images.githubusercontent.com/17754353/83843722-7711bb00-a6ba-11ea-8d7f-2285a14dc316.png">

I got onto creating an account and once I filled out the profile creation, I was taken to the mainly blank page that showed a small sentence at the top left corner saying that I can go ahead and set up my page. That is where I've been stuck on the loading screen. I had waited. As of now I've been waiting for over 3 minutes for it to load

**Comment by lleontan** [comment]
The algorithem takes time to load, give it a few more minutes.

**Comment by lleontan** [comment]
Duplicate issue. Closing.
