### ISSUE TITLE
MAJOR: Unable to add new interests as a new user

### ISSUE THREAD

**Issue by angelashen0607** [HappyHobby/HappyHobby#60]
**Description of issue:**
After signing up as a new user, I was unable to add new hobbies. (when I clicked on the set up new interests, the page just showed loading ... and didn't display any information even after being refreshed)

**Reproduction of steps:**

1. Sign up with random email and password as a new user (don't sign in using gmail)
2. Click on "set your interests" button

**Rationale:**
Setting up interests is probably the first step for users to start using the web app. If users cannot access interests or even get out of the loading page, they will not be able to proceed to the actual web app.

**Comment by angelashen0607** [comment]
I also can't click on settings when on the loading page. I tried signing out and logging in again but the system doesn't recognize the credentials that I used to sign up earlier.

**Comment by lleontan** [comment]
We're having trouble replicating this bug.

- Did you run locally with "NPM start" or did you visit "https://happyhobby-9aec1.web.app/"?
- Did you see a message saying to configure your profile after creating a new account on the homepage?
- Can you check the status of your internet connection and go to the settings page? Your symptoms are consistent with not having wifi.

I'm going to delete your gmail user in the database so you can create a new account.

**Comment by angelashen0607** [comment]
Yes, I did see configure your profile after creating a new acc and after I clicked on the set your interests it leads me to a loading page. 

I wasn't able to navigate to the settings page and I would assume if I don't have internet connection I won't be able to even reach the website?

**Comment by lleontan** [comment]
Thanks!
We will have a fix for it soon.
