### ISSUE TITLE
Minor: is the new hobby view intended onclick of logo?

### ISSUE THREAD

**Issue by ashleyvarma** [HappyHobby/HappyHobby#61]
Reproduction Steps:
1. Sign in with an existing account
2. View landing page
3. Click on site logo "Happy Hobby "in the top left
4. A new hobby is loaded on the screen

Description & Rationale: 
Clicking on the logo in the top left of the landing page allows the user to generate a new daily hobby activity (based on their preferences). If the daily hobby is intended to be done that day, giving users the option to cycle through many interests before landing on their preferred hobby could be easier displayed as a list view of potentials activities instead of this unidentified feature.

**Comment by lleontan** [comment]
Working as intented. We wanted to drip feed user's new hobbies within their interest while at the same time giving them the ability to skip ones they didn't like.
