### ISSUE TITLE
No Interests / Random Recommended

### ISSUE THREAD

**Issue by kevin-chiu** [HappyHobby/HappyHobby#63]
Describe the bug
I was given a random hobby because no likes or dislikes were chosen

To Reproduce

Go to 'Settings'
Remove all Interests
Click Confirm
Click on Happy Hobby Homepage

Expected behavior
I expected a larger notice explaining why I was given a random hobby. The recommended hobby overshadows my interests.

Screenshots
![image](https://user-images.githubusercontent.com/31137647/83925146-4de53f00-a73b-11ea-8ce2-1b02249ec59b.png)

**Comment by thejameskim** [comment]
Thanks for your feedback! Labeling this as an enhancement that can better the user experience.
