### ISSUE TITLE
no way to view previous hobby suggestions

### ISSUE THREAD

**Issue by pranita122** [HappyHobby/HappyHobby#69]
I understand that the web app is meant to show a different suggestion every time the page refreshes, however, on the chance that the user refreshes a page by mistake, but was interested in the previous suggestion, there is no way to view that hobby again. A simple search feature that covers your database might help with this, so the user can hit keywords and find their previous hobby.

**Comment by thejameskim** [comment]
Hey! Thanks for your feedback. As this doesn't break functionality and you can return to previous suggestion by refreshing the page until you return to the suggestion you want, I'm going to downgrade this to a minor enhancement. Also, we won't be able to complete this feature in this release as it would require storing the previous suggestions into a database.
